name: compile

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  compile:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build